import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { AngularFireStorage } from 'angularfire2/storage';

@Component({
  selector: 'app-fileuploader',
  templateUrl: './fileuploader.component.html',
  styleUrls: ['./fileuploader.component.css']
})
export class FileuploaderComponent implements OnInit {
  pageTitle: string;
  uploadPercent = 0;
  private uploadTask;

  constructor(private activatedRoute: ActivatedRoute, private afStorage: AngularFireStorage) { }

  ngOnInit() {
    this.activatedRoute.data.subscribe((dataObject) => {
      this.pageTitle = dataObject.pageTitle;
    });
  }

  uploadFile(file) {
    return new Promise((resolve, reject) => {
      // Gets unique identifier generated by p-fileUpload component
      const ref = this.afStorage.ref(
        file.objectURL.changingThisBreaksApplicationSecurity.split('/')[3]
      );

      this.uploadTask = ref.put(file).then((snapshot) => {
        resolve(snapshot);
      })
        .catch((error) => {
        reject(error);
      });

      this.uploadTask.percentageChanges().subscribe((value) => {
        console.log(this.uploadPercent);
        this.uploadPercent = Math.floor(value);
        console.log(this.uploadPercent);
      });
    });
  }

  uploadFiles(event) {
    Promise.all(event.files.map(async (file) => {
      return await this.uploadFile(file);
    }))
      .then(values => {
        console.log(values);
      })
      .catch((err) => {
        console.log(err);
      });
  }
}
